version: '2'

services:

#########################
#  PostgreSQL Database  #
#########################

    postgres:
        image: postgres:latest
        ports:
         - "5432:5432"        
        environment:
         -  POSTGRES_PASSWORD=syncope
         -  POSTGRES_USER=syncope
         -  POSTGRES_DB=syncope
#        volumes:
#         - ./db-init-scripts/:/docker-entrypoint-initdb.d/:ro
#         - postgresql_data:/var/lib/postgresql/data
#         - /etc/timezone:/etc/timezone:ro

#########################
#  Apache Syncope Core  #
#########################

    syncope-core:
      image: syncope-docker-core:2.0.2
      ports:
        - "8080:8080"
      volumes:
        - /var/log/apache-syncope:/tmp/log/apache-syncope/core:rw
      depends_on:
        -  postgres      

############################
#  Apache Syncope Console  #
############################

    syncope-console:
      image:  syncope-docker-console:2.0.2
      ports:
        - "9080:8080"
      volumes:
        - /var/log/apache-syncope:/tmp/log/apache-syncope/console:rw
      depends_on:
        - syncope-core

###############################
#  Apache Syncope Enduser UI  #
###############################

    syncope-enduser:
      image:  syncope-docker-enduser:2.0.2
      ports:
        - "7080:8080"
      volumes:
        - /var/log/apache-syncope:/tmp/log/apache-syncope/enduser:rw
      depends_on:
        - syncope-core
